### ISSUE TITLE
エスケープ処理の実装

### ISSUE THREAD

**Issue by kmno4hno3** [kmno4hno3/lamp_practice#4]
admin_view.phpにて商品名表示部をfunction.phpで定義したh()関数で
を実装しようと思います。

**Comment by thisprodigiousgeek** [comment]
issue作成ありがとうございます！
admin_viewはあくまで一例であり、XSSの脆弱性があるのはadmin_viewだけではありません。
全てのviewにおいてXSS対策をすることが重要ですね。
すべての出力箇所について対策を行いましょう！

**Comment by kmno4hno3** [comment]
分かりました。
ちなみに、6ファイル全てに対して変数を出力表示する部分に施そうと思います。
